### ISSUE TITLE
Blank window when login

### ISSUE THREAD

**Issue by Bob-YsPan** [minecraft-linux/mcpelauncher-webview#1]
Like the screenshots, when I want to login the Microsoft account, I get the blank window and not show any webpage, and when I'm tried to complie by AUR, it will cause segmentation fault.

My system:
Manjaro Linux(Latest)
Intel Core i5 8250U
Geforce 1050 Mobile

The Appimage's version
![image](https://github.com/minecraft-linux/mcpelauncher-webview/assets/46966555/b76cc9d7-29e0-426b-a098-da79637b48ee)

Tried to run the execuable directly
```bash
# No any output and exit after 1secs
ys-pan@X560UD-Linux ~ » ~/mcpelauncher_x86/usr/bin/mcpelauncher-webview "https://www.google.com"
# Blank window
ys-pan@X560UD-Linux ~ » ~/mcpelauncher_x86/usr/bin/mcpelauncher-webview StartUrl "https://www.google.com"
# No any output and exit after 1secs
ys-pan@X560UD-Linux ~ » ~/mcpelauncher_x86/usr/bin/mcpelauncher-webview StartUrl "https://www.google.com" EndUrl "https://www.youtube.com"
# The help print seems normal
ys-pan@X560UD-Linux ~ » ~/mcpelauncher_x86/usr/bin/mcpelauncher-webview --help                                                                                                                               255 ↵
Usage: /home/ys-pan/mcpelauncher_x86/usr/bin/mcpelauncher-webview [options] startUrl endUrl

Options:
  -h, --help  Displays this help.

Arguments:
  startUrl    The initial URL to open
  endUrl      The URL which will cause the webview to quit
ys-pan@X560UD-Linux ~ »
```

Complied by AUR
![image](https://github.com/minecraft-linux/mcpelauncher-webview/assets/46966555/ee37513c-02ed-491e-8717-2faf0458226b)

**Comment by ChristopherHX** [comment]
The usage of the tool is
```
~/mcpelauncher_x86/usr/bin/mcpelauncher-webview "https://www.google.com" "https://localhost"
```

arguments don't have a prefix and this tool is not meant to work at all without exactly 2 valid urls.

You can use cli xbox login, by using your chromium or firefox if your system cannot run qtwebengine.
Add these flags to the mcpelauncher-manifest cmake flags (Debug builds makes xbox cli login impossible)
```
cmake -DXAL_WEBVIEW_USE_QT=OFF -DXAL_WEBVIEW_USE_CLI=ON -DCMAKE_BUILD_TYPE=Release
```

You have to paste the xal end url from the browser devtools to complete login, this is the reason for the webview tool.

**Comment by Bob-YsPan** [comment]
I tried to add these flags into PKGBUILD, and make the package but with no luck...
I dosen't have the x86_64 package to test the function works.

But I found the solution at [this repo](https://github.com/vlaci/openconnect-sso/issues/69), add the command into the shell script then run the client into the appimage(or run webview into appimage directly), the webpage works.

If not work I also tried to clean the webview's data(at `~/.local/share/mcpelauncher-webview`)

```bash
$ export QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox"
```

**Comment by ChristopherHX** [comment]
> QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox"

That's what the AppImage does itself (except you provide QTWEBENGINE_CHROMIUM_FLAGS yourself) if the default entrypoint is used.
